source 'https://rubygems.org'
gem 'fastreader'
gem 'nokogiri', '1.8.1', :git => 'https://github.com/sparklemotion/nokogiri.git'
gem 'rack', '~> 2.2', '>= 2.2.14'
gem 'rspec', :git => 'https://github.com/rspec/rspec.git'
gem 'pdfkit', '~> 0.5'
